// Search phrases, written the way people in the Philippines actually type them
// into Google (lowercase, "ph" shorthand, Taglish). Feeds the keywords meta tag
// and the Dataset JSON-LD. Google ignores the keywords tag for ranking, so the
// highest-value phrases also live in SITE_TITLE / SITE_DESCRIPTION (lib/site.ts).

export const BRAND_KEYWORDS = [
  "SimplifyTrabaho",
  "Simplify Trabaho",
  "simplify jobs philippines",
  "simplify internships philippines",
  "simplifyjobs ph",
  "jobstreet alternative",
  "free job search philippines",
];

export const GENERAL_KEYWORDS = [
  "jobs philippines",
  "jobs in the philippines",
  "jobs ph",
  "job openings philippines",
  "job hiring philippines",
  "hiring philippines",
  "hiring now philippines",
  "hiring ph",
  "now hiring manila",
  "urgent hiring philippines",
  "job vacancies philippines",
  "careers philippines",
  "companies hiring philippines",
  "latest job openings philippines",
  "job search philippines",
  "trabaho",
  "trabaho philippines",
  "hanap trabaho",
  "naghahanap ng trabaho",
  "hiring ngayon",
  "may hiring ba",
  "saan may hiring",
];

export const INTERNSHIP_KEYWORDS = [
  "internships philippines",
  "internship philippines",
  "internship ph",
  "ph internships",
  "ojt philippines",
  "ojt hiring",
  "ojt hiring manila",
  "ojt for college students",
  "ojt for it students",
  "ojt for computer science students",
  "ojt for accounting students",
  "paid internship philippines",
  "paid ojt philippines",
  "remote internship philippines",
  "summer internship philippines",
  "internship for college students philippines",
  "it internship philippines",
  "software engineering internship philippines",
  "data internship philippines",
  "marketing internship philippines",
  "practicum philippines",
  "saan pwede mag ojt",
];

export const ENTRY_LEVEL_KEYWORDS = [
  "entry level jobs philippines",
  "entry level jobs ph",
  "fresh graduate jobs philippines",
  "fresh grad jobs ph",
  "hiring fresh graduates",
  "fresh graduate hiring manila",
  "jobs for fresh graduates no experience",
  "no experience jobs philippines",
  "first job philippines",
  "career starter jobs philippines",
  "junior developer jobs philippines",
  "trabaho para sa fresh grad",
];

export const WORK_SETUP_KEYWORDS = [
  "work from home jobs philippines",
  "wfh jobs philippines",
  "wfh jobs ph",
  "remote jobs philippines",
  "remote jobs ph",
  "online jobs philippines",
  "home based jobs philippines",
  "hybrid jobs philippines",
  "work from home hiring",
  "remote entry level jobs philippines",
];

export const LOCATION_KEYWORDS = [
  "jobs in metro manila",
  "jobs in manila",
  "jobs in makati",
  "jobs in bgc",
  "jobs in taguig",
  "jobs in ortigas",
  "jobs in pasig",
  "jobs in quezon city",
  "jobs in mandaluyong",
  "jobs in alabang",
  "jobs in cebu",
  "cebu it park jobs",
  "jobs in davao",
  "jobs in clark pampanga",
  "jobs in laguna",
  "jobs in cavite",
  "jobs in batangas",
  "jobs in iloilo",
  "jobs in bacolod",
  "jobs in baguio",
  "jobs in cagayan de oro",
];

export const FIELD_KEYWORDS = [
  "it jobs philippines",
  "tech jobs philippines",
  "software developer jobs philippines",
  "software engineer jobs philippines",
  "web developer jobs philippines",
  "programmer jobs philippines",
  "data analyst jobs philippines",
  "data science jobs philippines",
  "ui ux designer jobs philippines",
  "graphic designer jobs philippines",
  "customer service jobs philippines",
  "call center jobs philippines",
  "bpo jobs philippines",
  "csr hiring",
  "accounting jobs philippines",
  "finance jobs philippines",
  "bookkeeper jobs philippines",
  "marketing jobs philippines",
  "digital marketing jobs philippines",
  "sales jobs philippines",
  "hr jobs philippines",
  "recruiter jobs philippines",
  "nurse jobs philippines",
  "healthcare jobs philippines",
  "admin assistant jobs philippines",
  "operations jobs philippines",
  "engineering jobs philippines",
];

/** Every phrase once, in priority order — what the keywords meta tag gets. */
export const ALL_KEYWORDS = [
  ...new Set([
    ...BRAND_KEYWORDS,
    ...GENERAL_KEYWORDS,
    ...INTERNSHIP_KEYWORDS,
    ...ENTRY_LEVEL_KEYWORDS,
    ...WORK_SETUP_KEYWORDS,
    ...LOCATION_KEYWORDS,
    ...FIELD_KEYWORDS,
  ]),
];
