import { interleaveByCompany } from "./feed.js";
import type { Listing } from "./types.js";

// README.md generator (SPEC §11). The README is fully generated — the header
// comment warns hand-editors, and the pipeline overwrites it on every run.

const REPO_URL = "https://github.com/yanicells/SimplifyTrabaho";
const WEBSITE_URL = "https://simplifytrabaho.ycells.com";

const FEATURED_WINDOW_DAYS = 30;
const FEATURED_CAP = 200;
/** One bulk hirer can't fill the table: the site still lists all of its roles. */
const FEATURED_PER_COMPANY = 10;
const DAY_MS = 86_400_000;

export interface ReadmeInput {
  listings: Listing[];
  companiesTracked: number;
  /** ISO timestamp of this pipeline run. */
  updatedAt: string;
  /** Injectable clock for tests; defaults to updatedAt. */
  now?: string;
}

/** "2026-09-27T…" → "Sep 27". UTC so the date doesn't shift with the runner's zone. */
function shortDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    timeZone: "UTC",
  });
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").trim();
}

export function generateReadme({
  listings,
  companiesTracked,
  updatedAt,
  now,
}: ReadmeInput): string {
  const nowMs = Date.parse(now ?? updatedAt);
  const activeCount = listings.filter((l) => l.active).length;

  // Interleave and cap per company before the overall cap, so the 200 featured
  // rows span many companies instead of one bulk poster's block.
  const perCompany = new Map<string, number>();
  const featured = interleaveByCompany(
    listings
      .filter(
        (l) =>
          l.active &&
          l.companyType === "direct" &&
          (l.level === "internship" || l.level === "entry") &&
          nowMs - Date.parse(l.datePosted) <= FEATURED_WINDOW_DAYS * DAY_MS,
      )
      .sort((a, b) => b.datePosted.localeCompare(a.datePosted)),
    (l) => l.datePosted.slice(0, 10),
    (l) => l.company,
  )
    .filter((l) => {
      const seen = (perCompany.get(l.company) ?? 0) + 1;
      perCompany.set(l.company, seen);
      return seen <= FEATURED_PER_COMPANY;
    })
    .slice(0, FEATURED_CAP);

  const rows = featured.map((l) =>
    [
      "",
      `**${escapeCell(l.company)}**`,
      escapeCell(l.title),
      escapeCell(l.locations.join("; ")),
      `[Apply](${l.url})`,
      shortDate(l.datePosted),
      "",
    ]
      .join(" | ")
      .trim(),
  );

  const table =
    featured.length > 0
      ? [
          "| Company | Role | Location | Apply | Posted |",
          "| --- | --- | --- | --- | --- |",
          ...rows,
        ].join("\n")
      : "_No internship or entry-level roles posted in the last 30 days. Check the website for all roles._";

  const updatedStamp = updatedAt.slice(0, 16).replace("T", " ") + " UTC";
  const listingNoun = activeCount === 1 ? "listing" : "listings";
  const siteLabel = WEBSITE_URL.replace("https://", "");

  return `<!--
  THIS FILE IS GENERATED by \`pnpm refresh\`. Do not edit by hand.
  Edit pipeline/src/readme.ts instead. See docs/PIPELINE.md for how the data is built.
-->

# SimplifyTrabaho 🇵🇭

[![Daily refresh](${REPO_URL}/actions/workflows/refresh.yml/badge.svg)](${REPO_URL}/actions/workflows/refresh.yml) [![CI](${REPO_URL}/actions/workflows/ci.yml/badge.svg)](${REPO_URL}/actions/workflows/ci.yml)

A free, auto-updated list of jobs at Philippine companies, covering all roles and levels.
Internships and entry-level roles are featured below. It's the PH counterpart of
[SimplifyJobs/Summer2026-Internships](https://github.com/SimplifyJobs/Summer2026-Internships).

**${activeCount.toLocaleString("en-US")} active ${listingNoun} from ${companiesTracked.toLocaleString("en-US")} companies** · updated ${updatedStamp} · [Browse and filter everything at ${siteLabel}](${WEBSITE_URL}) · [How the listings get here](docs/PIPELINE.md)

## Where the listings come from

Every listing comes from the employer's own careers page. That means either the public
ATS feed the page loads (Greenhouse, Lever, Ashby, Workable, SmartRecruiters, Recruitee,
BambooHR, Breezy, Manatal, Pinpoint, Rippling, Teamtailor) or the company's Workday site.

We store only the company, title, location, work setup, dates, and link. We don't copy
job descriptions or keep recruiter names and emails, and every Apply link goes to the
company's own application page. The data refreshes once a day.

## Featured: internships & entry-level (last ${FEATURED_WINDOW_DAYS} days)

${table}

---

Full list with filters (all roles, all levels): **[${siteLabel}](${WEBSITE_URL})**

Want your company listed? Your jobs need to be on a supported ATS with a public board.
Open an issue at [${REPO_URL.replace("https://github.com/", "")}](${REPO_URL}), or see
[how companies get added](docs/PIPELINE.md#adding-a-company).

## License

Code is [MIT](LICENSE). The dataset (\`data/listings.json\`, \`pipeline/companies.json\`)
is [CC0 1.0](data/LICENSE), which is public domain. Attribution with a link back to
this repo is appreciated but not required.
`;
}
