import type { Listing } from "./types.js";

// README.md generator (SPEC §11). The README is fully generated — the header
// comment warns hand-editors, and the pipeline overwrites it on every run.

const REPO_URL = "https://github.com/yanicells/SimplifyTrabaho";
const WEBSITE_URL = "https://simplifytrabaho.ycells.com";

const FEATURED_WINDOW_DAYS = 30;
const FEATURED_CAP = 200;
const DAY_MS = 86_400_000;

export interface ReadmeInput {
  listings: Listing[];
  companiesTracked: number;
  /** ISO timestamp of this pipeline run. */
  updatedAt: string;
  /** Injectable clock for tests; defaults to updatedAt. */
  now?: string;
}

function relativeDays(fromIso: string, nowMs: number): string {
  const days = Math.floor((nowMs - Date.parse(fromIso)) / DAY_MS);
  if (days <= 0) return "today";
  return `${days}d ago`;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").trim();
}

const WORK_SETUP_LABEL: Record<Listing["workSetup"], string> = {
  onsite: "On-site",
  hybrid: "Hybrid",
  remote: "Remote",
  unknown: "—",
};

export function generateReadme({
  listings,
  companiesTracked,
  updatedAt,
  now,
}: ReadmeInput): string {
  const nowMs = Date.parse(now ?? updatedAt);
  const activeCount = listings.filter((l) => l.active).length;

  const featured = listings
    .filter(
      (l) =>
        l.active &&
        (l.level === "internship" || l.level === "entry") &&
        nowMs - Date.parse(l.datePosted) <= FEATURED_WINDOW_DAYS * DAY_MS,
    )
    .sort((a, b) => b.datePosted.localeCompare(a.datePosted))
    .slice(0, FEATURED_CAP);

  const rows = featured.map((l) =>
    [
      "",
      `**${escapeCell(l.company)}**`,
      escapeCell(l.title),
      escapeCell(l.locations.join("; ")),
      WORK_SETUP_LABEL[l.workSetup],
      `[Apply](${l.url})`,
      relativeDays(l.datePosted, nowMs),
      "",
    ]
      .join(" | ")
      .trim(),
  );

  const table =
    featured.length > 0
      ? [
          "| Company | Role | Location | Work Setup | Apply | Posted |",
          "| --- | --- | --- | --- | --- | --- |",
          ...rows,
        ].join("\n")
      : "_No internship or entry-level roles posted in the last 30 days — check the website for all roles._";

  const updatedStamp = updatedAt.slice(0, 16).replace("T", " ") + " UTC";
  const listingNoun = activeCount === 1 ? "listing" : "listings";

  return `<!--
  ⚠️ THIS FILE IS GENERATED by \`pnpm refresh\` — do not edit by hand.
  Edit pipeline/src/readme.ts instead. See docs/SPEC.md §11.
-->

# SimplifyTrabaho 🇵🇭

[![Daily refresh](${REPO_URL}/actions/workflows/refresh.yml/badge.svg)](${REPO_URL}/actions/workflows/refresh.yml) [![CI](${REPO_URL}/actions/workflows/ci.yml/badge.svg)](${REPO_URL}/actions/workflows/ci.yml)

A free, open, automatically updated list of jobs at Philippine companies — all roles,
all levels — with **internships and entry-level roles featured**. Inspired by
[SimplifyJobs/Summer2026-Internships](https://github.com/SimplifyJobs/Summer2026-Internships),
built for the PH market.

**🌐 Full list with filters → [${WEBSITE_URL.replace("https://", "")}](${WEBSITE_URL})** · [Spec](docs/SPEC.md) · [Roadmap](ROADMAP.md)

## How this works (and why it's legal)

Listings come exclusively from public ATS APIs (Greenhouse, Lever, Ashby, Workable,
SmartRecruiters, Recruitee) that companies intentionally publish for their own careers
pages. We store facts only — company, role title, location, link — and always send you
to the company's official application page. No job boards are scraped. Ever. Data
refreshes once daily.

## ✨ Featured: internships & entry-level (last ${FEATURED_WINDOW_DAYS} days)

${table}

---

📊 **${activeCount} active ${listingNoun}** from **${companiesTracked} companies tracked** · last updated ${updatedStamp}

➡️ Full list with filters (all roles, all levels): **[${WEBSITE_URL.replace("https://", "")}](${WEBSITE_URL})**

Want your company listed? Your jobs just need to be on a supported ATS with a public
board — open an issue at [${REPO_URL.replace("https://github.com/", "")}](${REPO_URL}).

## License

Code is [MIT](LICENSE). The dataset (\`data/listings.json\`, \`pipeline/companies.json\`)
is [CC0 1.0](data/LICENSE) — public domain. Attribution with a link back to this repo
is appreciated but not required.
`;
}
